development:
  adapter: mysql2
  encoding: utf8
  database: fulfilist_dev
  pool: 5

test:
  adapter: mysql2
  encoding: utf8
  database: fulfilist_test
  pool: 5
  
production:
  adapter: mysql2
  encoding: utf8
  database: fulfilist_production
  pool: 5

